fc_django/urls.py
from django.contrib import admin
from django.urls import path
from fcuser.views import index
from fcuser.views import RegisterView, LoginView, logout
from product.views import ProductList, ProductCreate, ProductDetail, ProductListAPI, ProductDetailAPI
from order.views import OrderCreate, OrderList 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('register/',RegisterView.as_view()),
    path('login/',LoginView.as_view()),
    path('product/',ProductList.as_view()),
    path('product/create/',ProductCreate.as_view()),
    path('product/<int:pk>/',ProductDetail.as_view()),
    path('order/create/',OrderCreate.as_view()),
    path('order/',OrderList.as_view()),
    path('logout/',logout),
    path('api/product/', ProductListAPI.as_view()),
    path('api/product/<int:pk>', ProductDetailAPI.as_view()),


]

product/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=256, verbose_name='상품명')
    price = models.IntegerField(verbose_name='상품가격')
    description = models.TextField(verbose_name='상품설명')
    stock = models.IntegerField(verbose_name='재고')
    register_date = models.DateTimeField(auto_now_add = True, verbose_name='등록날짜')

    def __str__(self):
        return self.name


    class Meta:
        db_table = 'Jang_product'
        verbose_name = '상품'
        verbose_name_plural = '상품'

product/forms.py
from django import forms
from .models import Product

class RegisterForm(forms.Form):
    name = forms.CharField(
        error_messages={'required': '상품명을 입력해주세요.'}, max_length=128, label='상품명' # 폼에서는 라벨, 모델에서는 verbose_name
    )
    price = forms.IntegerField(
        error_messages={'required': '상품가격을 입력해주세요.'}, label='상품가격'
    )
    description = forms.CharField(
        error_messages={'required': '상품설명을 입력해주세요'}, label='상품설명'
    )
    stock = forms.IntegerField(
        error_messages={'required': '재고를 입력해주세요'}, label='재고'
    )
    
    def clean(self):
        cleaned_data = super().clean()
        name = self.cleaned_data.get('name')
        price = self.cleaned_data.get('price')
        description = self.cleaned_data.get('description')
        stock = self.cleaned_data.get('stock')

        if not (name and price and description and stock):
            self.add_error('name', '상품명값이 없습니다.')
            self.add_error('price', '가격값이 없습니다.')
            self.add_error('description', '상품설명값이 없습니다.')
            self.add_error('stock', '재고값이 없습니다.')


                
    
    

product/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView
from .models import Product
from .forms import RegisterForm
from order.forms import RegisterForm as OrderForm
from django.utils.decorators import method_decorator
from fcuser.decorators import admin_required
from fcuser.models import Fcuser
from rest_framework import generics
from rest_framework import mixins
from .serializers import ProductSerializer
# Create your views here.

class ProductListAPI(generics.GenericAPIView, mixins.ListModelMixin):
    serializer_class = ProductSerializer

    def get_queryset(self):
        return Product.objects.all().order_by('id')

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)


class ProductDetailAPI(generics.GenericAPIView, mixins.RetrieveModelMixin):
    serializer_class = ProductSerializer

    def get_queryset(self):
        return Product.objects.all().order_by('id')

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs) # list와 유일한 차이점은 url 지정하는 곳에서 pk를 지정해야 한다는 것


class ProductList(ListView): # 리스트 뷰는 별도의 폼을 만들지 않는다.
    model = Product # 어떤 모델의 리스트를 조회할 것인 지 지정해준다 
    template_name = 'product.html'
    # context_object_name = 'product_list' # 이걸 따로 지정안하면 product.html 파일에서 object_list라고 쓰면 데이터가 웹에서 보였는 데 object_list라는 명칭이 싫을 때 바꾸는 기능

@method_decorator(admin_required, name='dispatch')
class ProductCreate(FormView):
    template_name = 'register_product.html'
    form_class = RegisterForm
    success_url = '/product/' 

    def form_valid(self,form):
        product = Product(
            name=form.data.get('name'),
            price=form.data.get('price'),
            description=form.data.get('description'),
            stock=form.data.get('stock')
        )
        product.save()
        return super().form_valid(form)


class ProductDetail(DetailView):
    queryset = Product.objects.all() # 디테일뷰는 쿼리문을 이용해서 모든 제품들 중에서 하나씩 꺼내서 사용할 것임. 그래서 일단 다 꺼내놓은 것
    template_name = 'product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs): # 자세히보기 페이지에서 주문하기 기능을 위해선 해당 폼을 가져와야하는데 이 함수를 통해서 그 기능을 구현한다.
        context = super().get_context_data(**kwargs) # 디테일 뷰에 있는 데이터를 먼저 만들고나서 내가 만들고자 하는 것을 추가하는 것
        context['form'] = OrderForm(self.request) # orderform은 오더폴더에서 가져온 registerform을 앨리아스 한 것이고 뷰클래스에는 셀프안에 리퀘스트가 있다. 그래서 그냥 적어넣으면 됨
                                                  # 그러면 저 리퀘스트를 통해 order폴더 안에 있는 registerform의 리퀘스트와 연동됨. 
        return context
        

product/templates/product.html
{% extends "base.html" %}
{% load humanize %}
<!-- 휴머나이즈는 여러 표현(?)을 할 수 있는 기능. ex) 1200000 -> 1,200,000 원 / 사용하려면 settings.py에 휴머나이즈 앱을 활성화 -->
{% block header %}
<script>
    function product_detail(id){
        $.ajax({
            url: "/api/product/" + id,
            // 우리가 ProductListAPI라는 클래스를 만든 것을 활용하는 것임
            success: function( result ) {
                // product_detail에 지정한 url을 통해서 가져온 데이터들이 result안에 들어감
                $("#product-" + id).popover({
                    html: true,
                    // html 태그를 사용할 것이다라는 의미
                    content: result.name + "<br/>" + result.price
                }).popover('show');
            }
        });
    }
    function product_leave(id) {
        $("#product-" + id).popover('hide');
    }
    $(document).ready(function() {
    // 현재 웹페이지가 준비가 됐을 때 함수를 호출할게요
    });
</script>
{%  endblock%}
{% block contents %}
<div class='row mt-5'>
    <div class="col-12">
        <h1 style="text-align: center;">상품리스트</h1>
    </div>
</div>

<div class='row mt-5'>
    <div class="col-12">
        <table class="table table-light">
            <thead class="thead-light">
                <tr>
                    <th scope="col">번호</th>
                    <th scope="col">상품명</th>
                    <th scope="col">가격</th>
                    <th scope="col">등록날짜</th>
                </tr>
            </thead>
            <tbody class="text-dark">
                    <!-- {{ object_list }} 이걸 넣으면 <QuerySet [<Product: 식기세척기>]> 이렇게 나옴 -->
                {% for product in object_list %}
                <tr>
                    <th scope="row">{{ product.id }}</th>
                    <th><a id="product-{{ product.id }}" onmouseenter="product_detail({{ product.id }})" onmouseleave="product_leave({{ product.id }})" style="cursor: pointer;" href="/product/{{ product.id }}">{{ product.name }}</a></th>
                    <th>{{ product.price|intcomma }} 원</th>
                    <th>{{ product.register_date|date:'Y-m-d H:i' }}</th>  
                </tr>
                    <!-- {{ product.name }} : {{ product.price }} -->
                    <!-- 식기세척기 : 1200000 이렇게 나옴 -->
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

product/templates/product_detail.html
{% extends "base.html" %}
{% load humanize %}
<!-- 휴머나이즈는 여러 표현(?)을 할 수 있는 기능. ex) 1200000 -> 1,200,000 원 / 사용하려면 settings.py에 휴머나이즈 앱을 활성화 -->
{% block contents %}
<div class='row mt-5'>
    <div class="col-12">
        <h1 style="text-align: center;">{{ product.name }} 상품 자세히 보기</h1>
    </div>
</div>

<div class='row mt-5'>
    <div class="col-12">
        <div class="card" style="width : 100%">
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"> 
                    <form method="POST" action="/order/create/">
                        {% csrf_token %}
                        <!-- 자세히보기 페이지에서 주문하기기능을 만들어서 주문하기 버튼을 누르게 되면 action에 지정한 url로 이동해서 밑에 있는 폼을 부르는 작업들이 실행됨 이때 폼데이터를 실어 보내줘야 되므로 method는 POST이다.-->
                        {% for field in form %}
                        <div class="form-group">
                            <!-- Order 밑에 있는 RegisterForm 에 prodcut필드는 히든인풋으로 인풋은 되지만 클라이언트에게는 숨긴 필드이다. 그래서 프로덕트가 아니면 라벨을 보여주고 프로덕트면 라벨을 숨긴다는 기능 -->
                            {% ifnotequal field.name 'product'  %}
                            <label for="{{ field.id_for_label}}">{{ field.label }}</label>
                            {% endifnotequal%}
                            <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label}}" placeholder="{{ field.label }}" name="{{ field.name }}" value="{% ifequal field.name 'product' %} {{ product.id }} {% endifequal %}" />
                            <!-- value를 넣은 이유는 클라이언트한테는 안보여도 product의 id 값이 value를 통해서 전달은 되도록 하기 위해서 -->
                        </div>
                        {% if field.errors %}
                        <span style="color:red">{{ field.errors }}</span>
                        {% endif %}
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">주문하기</button>
                    </form>
                </li>
                <li class="list-group-item">가격: {{ product.price|intcomma }} 원 </li>
                <li class="list-group-item">등록날짜: {{ product.register_date|date:'Y-m-d H:i' }}</li>
                <li class="list-group-item">재고: {{ product.stock }} 개</li>
                <li class="list-group-item">{{ product.description|safe }}</li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <a href="/product/">목록보기</a>
        </div>
    </div>
</div>
{% endblock %}

product/templates/register_product.html
{% extends "base.html" %}

<!-- 이하는 섬머노트위즈윅스 cdn파일 -->
{% block header %}
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
<script>
    $(document).ready(function () {
        $('#id_description').summernote({height:300});
        // 우리 코드에는 {{ field.id_for_label }}로 아이디가 설정돼있으므로 #id_description으로 설정함 
    });
</script>
{% endblock %}

{% block contents %}
<div class="row mt-5">
    <div class="col-12 text-center">
        <h1>상품등록</h1>
    </div>
</div>
<div class="row mt-5">
    <div class="col-12">
        {{ error }}
    </div>
</div>
<div class="row mt-5">
    <div class="col-12">
        <form method="POST" action=".">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label}}">{{ field.label }}</label>
                {% ifequal field.name 'description' %}
                <textarea class="form-control" name="{{ field.name }}" id="{{ field.id_for_label }}"></textarea>
                {% else %}
                <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label}}"
                    placeholder="{{ field.label }}" name="{{ field.name }}" />
                {% endifequal %}
            </div>
            {% if field.errors %}
            <span style="color:red">{{ field.errors }}</span>
            {% endif %}
            {% endfor %}
            <button type="submit" class="btn btn-primary">등록</button>
        </form>
    </div>
</div>

{% endblock %}